### ISSUE TITLE
Shortend user description duplication

### ISSUE THREAD

**Issue by Bitbored** [spark/spark.github.io#7]
When checking out the Particle community I clicked on some random members to see who they are (i.e, I opened their user card), and I notice that suddenly they all had the same user description in the user card.

Apparently this was caused by opening @moors7's (https://community.particle.io/users/moors7) user card. When clicking on his avatar, I see the following error in Google Chrome:
```
Uncaught TypeError: Cannot read property 'nodeValue' of undefined    14188:24
```

After this, the short user description of all users is that of @moors7. Also note that no trailing `...` is shown to show that the text has been shortened.

I tried to reproduce this, and it does not seem to be caused by the :wink: emoticon, however newlines at certain locations (based on the character width of previous characters) seem to make this border case appear.

**Comment by moors7** [comment]
I'm just fabulous, and Discourse want you to know it ;) 
I too have seen this behavior, with other members, as well. Seeing as a page refresh fixed the issue, I never really thought too much about it. It only happens sporadically, and isn't a big turn-off (who wouldn't want to see my profile :p?!). That said, maybe someone can take a look at it, knowing there are more people noticing this. (I think a forum update would help, since it seems to work properly on Staging).

This seems similar: https://meta.discourse.org/t/user-cards-with-hr-s-cause-wrong-descriptions/23538

**Comment by Bitbored** [comment]
Mmmh, I'm only now aware the Discourse forum is not hosted on spark.github.io, and has nothing to to with this repo...

I guess it's best if I move this issue over to Discourse's issue tracker. I did not know the community website used discourse.
